// Generated by SpecAlive from the IR (specalive/generate/modelica.py). Regenerate, do not edit.
package two_tank_sequence "Two-tank fill/transfer/drain demonstrator: TK-101 is filled through XV-101, transferred to TK-102 through XV-102 and drained through XV-103, sequenced by PLC-101 from LT-101/LT-102 levels and START/STOP/SHUT pushbuttons. Hand-written golden IR from the L1 bundle with the CR-004 effective parameter set."
  package SpecAlive "Lightweight equation-based components the catalogue can target"
    package Interfaces "Connectors of the SpecAlive components"
      connector RealInput = Modelica.Blocks.Interfaces.RealInput "Real signal input";
      connector RealOutput = Modelica.Blocks.Interfaces.RealOutput "Real signal output";
      connector BooleanInput = Modelica.Blocks.Interfaces.BooleanInput "Boolean signal input";
      connector BooleanOutput = Modelica.Blocks.Interfaces.BooleanOutput "Boolean signal output";
      connector VolumeFlowInput = input Real(unit = "m3/s") "Volume flow rate set by the connected component";
      connector VolumeFlowOutput = output Real(unit = "m3/s") "Volume flow rate set by this component";
    end Interfaces;

    package Components "Component classes used by this model"
      model CommandButton "Momentary pushbutton: true for one pulse width from each press time"
        parameter Real pressTimes[:](each unit = "s") = fill(0.0, 0) "Press times; none means never pressed";
        parameter Real width(unit = "s") = 1 "Pulse width of one press";
        SpecAlive.Interfaces.BooleanOutput y "True while pressed";
      algorithm
        y := false;
        for i in 1:size(pressTimes, 1) loop
          if time >= pressTimes[i] and time < pressTimes[i] + width then
            y := true;
          end if;
        end for;
      end CommandButton;

      model FluidSink "Ideal drain boundary: accepts whatever flow arrives"
        SpecAlive.Interfaces.VolumeFlowInput inlet "Flow delivered by the upstream component";
      end FluidSink;

      model FluidSource "Ideal supply boundary: delivers whatever flow downstream draws"
        SpecAlive.Interfaces.VolumeFlowInput outlet "Flow drawn by the downstream component";
      end FluidSource;

      model OnOffValve "Ideal Boolean flow switch: passes its nominal flow when open, none when closed"
        parameter Real q_nominal(unit = "m3/s") "Flow when open";
        SpecAlive.Interfaces.VolumeFlowOutput inlet "Flow drawn from upstream";
        SpecAlive.Interfaces.VolumeFlowOutput outlet "Flow delivered downstream";
        SpecAlive.Interfaces.BooleanInput open "True commands the valve open";
      equation
        outlet = if open then q_nominal else 0;
        inlet = outlet;
      end OnOffValve;

      model Tank "Open tank of constant cross-section: the level integrates inflow minus outflow"
        parameter Real A(unit = "m2") "Cross-section area";
        parameter Real h_start(unit = "m") "Initial level";
        SpecAlive.Interfaces.VolumeFlowInput inlet "Inflow, set by the upstream component";
        SpecAlive.Interfaces.VolumeFlowInput outlet "Outflow, set by the downstream component";
        SpecAlive.Interfaces.RealOutput level(unit = "m") "Liquid level";
        Real h(unit = "m", start = h_start, fixed = true) "Liquid level";
      equation
        der(h) = (inlet - outlet) / A;
        level = h;
      end Tank;
    end Components;
  end SpecAlive;

  model Controller_plc_101_sequence "State machine plc_101_sequence of Sequence controller [IR plc_101_sequence]"
    // ASSUMPTION as_event_driven_controller: The controller reacts to events and thresholds immediately rather than on its 100 ms scan; the scan time is recorded but not simulated.
    type State = enumeration(
      idle "IDLE",
      fill_t1 "FILL_T1",
      wait_after_fill "WAIT_AFTER_FILL",
      transfer_t1_t2 "TRANSFER_T1_T2",
      wait_after_transfer "WAIT_AFTER_TRANSFER",
      drain_t2 "DRAIN_T2",
      wait_after_drain "WAIT_AFTER_DRAIN",
      paused "PAUSED",
      shutdown "SHUTDOWN");
    SpecAlive.Interfaces.RealInput level1(unit = "m") "[IR plc_101_level1]";
    SpecAlive.Interfaces.RealInput level2(unit = "m") "[IR plc_101_level2]";
    SpecAlive.Interfaces.BooleanInput start "[IR plc_101_start]";
    SpecAlive.Interfaces.BooleanInput stop "[IR plc_101_stop]";
    SpecAlive.Interfaces.BooleanInput shut "[IR plc_101_shut]";
    SpecAlive.Interfaces.BooleanOutput valve1 "[IR plc_101_valve1]";
    SpecAlive.Interfaces.BooleanOutput valve2 "[IR plc_101_valve2]";
    SpecAlive.Interfaces.BooleanOutput valve3 "[IR plc_101_valve3]";
    parameter Real plc_101_wait_after_drain(unit = "s") "[IR plc_101_wait_after_drain]";
    parameter Real plc_101_wait_after_fill(unit = "s") "[IR plc_101_wait_after_fill]";
    parameter Real plc_101_wait_after_transfer(unit = "s") "[IR plc_101_wait_after_transfer]";
    parameter Real tk_101_high_level(unit = "m") "[IR tk_101_high_level]";
    parameter Real tk_101_low_level(unit = "m") "[IR tk_101_low_level]";
    parameter Real tk_102_low_level(unit = "m") "[IR tk_102_low_level]";
    State state(start = State.idle, fixed = true) "Active state";
    State history_state(start = State.idle, fixed = true) "State a history return goes back to";
    discrete Real wait_after_fill_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_fill_timer]";
    discrete Real wait_after_fill_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_fill_timer]";
    discrete Real wait_after_transfer_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_transfer_timer]";
    discrete Real wait_after_transfer_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_transfer_timer]";
    discrete Real wait_after_drain_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_drain_timer]";
    discrete Real wait_after_drain_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_drain_timer]";
  algorithm
    when {
        edge(start),
        edge(stop),
        edge(shut),
        pre(state) == State.fill_t1 and level1 >= tk_101_high_level,
        pre(state) == State.wait_after_fill and time >= wait_after_fill_timer_deadline,
        pre(state) == State.transfer_t1_t2 and level1 <= tk_101_low_level,
        pre(state) == State.wait_after_transfer and time >= wait_after_transfer_timer_deadline,
        pre(state) == State.drain_t2 and level2 <= tk_102_low_level,
        pre(state) == State.wait_after_drain and time >= wait_after_drain_timer_deadline,
        pre(state) == State.shutdown and level1 <= tk_101_low_level and level2 <= tk_102_low_level} then
      if pre(state) == State.idle then
        if edge(shut) then
          // IR tr_idle_shut: IDLE -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(start) then
          // IR tr_idle_start: IDLE -> FILL_T1
          state := State.fill_t1;
        end if;
      elseif pre(state) == State.fill_t1 then
        if edge(shut) then
          // IR tr_fill_t1_shut: FILL_T1 -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_fill_t1_stop: FILL_T1 -> PAUSED
          history_state := State.fill_t1;
          state := State.paused;
        elseif level1 >= tk_101_high_level then
          // IR tr_fill_t1_high: FILL_T1 -> WAIT_AFTER_FILL
          wait_after_fill_timer_deadline := time + plc_101_wait_after_fill;
          state := State.wait_after_fill;
        end if;
      elseif pre(state) == State.wait_after_fill then
        if edge(shut) then
          // IR tr_wait_after_fill_shut: WAIT_AFTER_FILL -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_wait_after_fill_stop: WAIT_AFTER_FILL -> PAUSED
          history_state := State.wait_after_fill;
          wait_after_fill_timer_remaining := wait_after_fill_timer_deadline - time;
          state := State.paused;
        elseif time >= wait_after_fill_timer_deadline then
          // IR tr_wait_after_fill_done: WAIT_AFTER_FILL -> TRANSFER_T1_T2
          state := State.transfer_t1_t2;
        end if;
      elseif pre(state) == State.transfer_t1_t2 then
        if edge(shut) then
          // IR tr_transfer_t1_t2_shut: TRANSFER_T1_T2 -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_transfer_t1_t2_stop: TRANSFER_T1_T2 -> PAUSED
          history_state := State.transfer_t1_t2;
          state := State.paused;
        elseif level1 <= tk_101_low_level then
          // IR tr_transfer_t1_t2_low: TRANSFER_T1_T2 -> WAIT_AFTER_TRANSFER
          wait_after_transfer_timer_deadline := time + plc_101_wait_after_transfer;
          state := State.wait_after_transfer;
        end if;
      elseif pre(state) == State.wait_after_transfer then
        if edge(shut) then
          // IR tr_wait_after_transfer_shut: WAIT_AFTER_TRANSFER -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_wait_after_transfer_stop: WAIT_AFTER_TRANSFER -> PAUSED
          history_state := State.wait_after_transfer;
          wait_after_transfer_timer_remaining := wait_after_transfer_timer_deadline - time;
          state := State.paused;
        elseif time >= wait_after_transfer_timer_deadline then
          // IR tr_wait_after_transfer_done: WAIT_AFTER_TRANSFER -> DRAIN_T2
          state := State.drain_t2;
        end if;
      elseif pre(state) == State.drain_t2 then
        if edge(shut) then
          // IR tr_drain_t2_shut: DRAIN_T2 -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_drain_t2_stop: DRAIN_T2 -> PAUSED
          history_state := State.drain_t2;
          state := State.paused;
        elseif level2 <= tk_102_low_level then
          // IR tr_drain_t2_low: DRAIN_T2 -> WAIT_AFTER_DRAIN
          wait_after_drain_timer_deadline := time + plc_101_wait_after_drain;
          state := State.wait_after_drain;
        end if;
      elseif pre(state) == State.wait_after_drain then
        if edge(shut) then
          // IR tr_wait_after_drain_shut: WAIT_AFTER_DRAIN -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(stop) then
          // IR tr_wait_after_drain_stop: WAIT_AFTER_DRAIN -> PAUSED
          history_state := State.wait_after_drain;
          wait_after_drain_timer_remaining := wait_after_drain_timer_deadline - time;
          state := State.paused;
        elseif time >= wait_after_drain_timer_deadline then
          // IR tr_wait_after_drain_done: WAIT_AFTER_DRAIN -> FILL_T1
          state := State.fill_t1;
        end if;
      elseif pre(state) == State.paused then
        if edge(shut) then
          // IR tr_paused_shut: PAUSED -> SHUTDOWN
          history_state := State.idle;
          state := State.shutdown;
        elseif edge(start) then
          // IR tr_paused_start: PAUSED -> history
          state := history_state;
          if history_state == State.wait_after_fill then wait_after_fill_timer_deadline := time + wait_after_fill_timer_remaining; end if;
          if history_state == State.wait_after_transfer then wait_after_transfer_timer_deadline := time + wait_after_transfer_timer_remaining; end if;
          if history_state == State.wait_after_drain then wait_after_drain_timer_deadline := time + wait_after_drain_timer_remaining; end if;
        end if;
      elseif pre(state) == State.shutdown then
        if level1 <= tk_101_low_level and level2 <= tk_102_low_level then
          // IR tr_shutdown_done: SHUTDOWN -> IDLE
          state := State.idle;
        end if;
      end if;
    end when;
  equation
    valve1 = state == State.fill_t1;
    valve2 = state == State.transfer_t1_t2 or state == State.shutdown;
    valve3 = state == State.drain_t2 or state == State.shutdown;
    assert(not (valve1 and valve2) and (not (valve2 and valve3) or state == State.shutdown), "ac_08: Normal automatic operation shall never command V1 and V2 simultaneously, nor V2 and V3 simultaneously. The latter combination is permitted only in SHUTDOWN.");
  end Controller_plc_101_sequence;

  model System "two_tank_sequence: one instance per IR part and one connect per IR connection"
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    parameter Real pb_shut_press_times[1](each unit = "s") = {700.0} "pb_shut press_times, verification only [IR pb_shut_press_times]";
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    parameter Real pb_start_press_times[2](each unit = "s") = {20.0, 280.0} "pb_start press_times, verification only [IR pb_start_press_times]";
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    parameter Real pb_stop_press_times[2](each unit = "s") = {220.0, 650.0} "pb_stop press_times, verification only [IR pb_stop_press_times]";
    // ASSUMPTION as_event_driven_controller: The controller reacts to events and thresholds immediately rather than on its 100 ms scan; the scan time is recorded but not simulated.
    parameter Real plc_101_scan_time(unit = "s") = 0.1 "plc_101 scan_time [IR plc_101_scan_time]";
    parameter Real plc_101_wait_after_drain(unit = "s") = 8.0 "plc_101 wait_after_drain [IR plc_101_wait_after_drain]";
    parameter Real plc_101_wait_after_fill(unit = "s") = 10.0 "plc_101 wait_after_fill [IR plc_101_wait_after_fill]";
    parameter Real plc_101_wait_after_transfer(unit = "s") = 12.0 "plc_101 wait_after_transfer [IR plc_101_wait_after_transfer]";
    parameter Real system_state_timing_tolerance(unit = "s") = 2.0 "system state_timing_tolerance, verification only [IR system_state_timing_tolerance]";
    parameter Real system_stop_time(unit = "s") = 900.0 "system stop_time, verification only [IR system_stop_time]";
    parameter Real tk_101_area(unit = "m2") = 1.2 "tk_101 area [IR tk_101_area]";
    parameter Real tk_101_height(unit = "m") = 1.0 "tk_101 height [IR tk_101_height]";
    parameter Real tk_101_high_level(unit = "m") = 0.8 "tk_101 high_level [IR tk_101_high_level]";
    parameter Real tk_101_initial_level(unit = "m") = 0.05 "tk_101 initial_level [IR tk_101_initial_level]";
    parameter Real tk_101_low_level(unit = "m") = 0.05 "tk_101 low_level [IR tk_101_low_level]";
    parameter Real tk_101_max_working_level(unit = "m") = 0.9 "tk_101 max_working_level [IR tk_101_max_working_level]";
    parameter Real tk_102_area(unit = "m2") = 1.4 "tk_102 area [IR tk_102_area]";
    parameter Real tk_102_height(unit = "m") = 1.0 "tk_102 height [IR tk_102_height]";
    parameter Real tk_102_initial_level(unit = "m") = 0.05 "tk_102 initial_level [IR tk_102_initial_level]";
    parameter Real tk_102_low_level(unit = "m") = 0.05 "tk_102 low_level [IR tk_102_low_level]";
    parameter Real tk_102_max_working_level(unit = "m") = 0.9 "tk_102 max_working_level [IR tk_102_max_working_level]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    parameter Real xv_101_nominal_flow(unit = "m3/s") = 0.006 "xv_101 nominal_flow [IR xv_101_nominal_flow]";
    parameter Real xv_101_open_stroke_time(unit = "s") = 0.8 "xv_101 open_stroke_time [IR xv_101_open_stroke_time]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    parameter Real xv_102_nominal_flow(unit = "m3/s") = 0.0045 "xv_102 nominal_flow [IR xv_102_nominal_flow]";
    parameter Real xv_102_open_stroke_time(unit = "s") = 0.8 "xv_102 open_stroke_time [IR xv_102_open_stroke_time]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    parameter Real xv_103_nominal_flow(unit = "m3/s") = 0.005 "xv_103 nominal_flow [IR xv_103_nominal_flow]";
    parameter Real xv_103_open_stroke_time(unit = "s") = 0.8 "xv_103 open_stroke_time [IR xv_103_open_stroke_time]";

    SpecAlive.Components.FluidSink drn_101 "Drain [IR drn_101]";
    // ASSUMPTION as_ideal_level_sensor: Level transmitters report the tank level exactly, with no 4-20 mA scaling, noise, delay or bad-quality handling.
    Modelica.Blocks.Routing.RealPassThrough lt_101 "Tank 1 level transmitter [IR lt_101]";
    // ASSUMPTION as_ideal_level_sensor: Level transmitters report the tank level exactly, with no 4-20 mA scaling, noise, delay or bad-quality handling.
    Modelica.Blocks.Routing.RealPassThrough lt_102 "Tank 2 level transmitter [IR lt_102]";
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    SpecAlive.Components.CommandButton pb_shut(pressTimes = pb_shut_press_times) "SHUT pushbutton [IR pb_shut]";
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    SpecAlive.Components.CommandButton pb_start(pressTimes = pb_start_press_times) "START pushbutton [IR pb_start]";
    // ASSUMPTION as_momentary_pulse: No pulse width is given for the pushbuttons; each press is assumed to be true for one 1 s logging interval, as in the reference trace. Only its rising edge matters.
    SpecAlive.Components.CommandButton pb_stop(pressTimes = pb_stop_press_times) "STOP pushbutton [IR pb_stop]";
    // ASSUMPTION as_event_driven_controller: The controller reacts to events and thresholds immediately rather than on its 100 ms scan; the scan time is recorded but not simulated.
    Controller_plc_101_sequence plc_101(plc_101_wait_after_drain = plc_101_wait_after_drain, plc_101_wait_after_fill = plc_101_wait_after_fill, plc_101_wait_after_transfer = plc_101_wait_after_transfer, tk_101_high_level = tk_101_high_level, tk_101_low_level = tk_101_low_level, tk_102_low_level = tk_102_low_level) "Sequence controller [IR plc_101]";
    SpecAlive.Components.FluidSource src_101 "Supply source [IR src_101]";
    SpecAlive.Components.Tank tk_101(A = tk_101_area, h_start = tk_101_initial_level) "Tank 1 [IR tk_101]";
    SpecAlive.Components.Tank tk_102(A = tk_102_area, h_start = tk_102_initial_level) "Tank 2 [IR tk_102]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    SpecAlive.Components.OnOffValve xv_101(q_nominal = xv_101_nominal_flow) "Inlet valve to Tank 1 [IR xv_101]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    SpecAlive.Components.OnOffValve xv_102(q_nominal = xv_102_nominal_flow) "Transfer valve Tank 1 to Tank 2 [IR xv_102]";
    // ASSUMPTION as_constant_flow: Each valve passes its constant nominal flow when commanded open and none when closed, independent of tank level; valve stroke time is neglected.
    SpecAlive.Components.OnOffValve xv_103(q_nominal = xv_103_nominal_flow) "Tank 2 drain valve [IR xv_103]";
  equation
    connect(lt_101.y, plc_101.level1) "level measurement [IR if_ctl_01]";
    connect(lt_102.y, plc_101.level2) "level measurement [IR if_ctl_02]";
    connect(pb_start.y, plc_101.start) "command [IR if_ctl_03]";
    connect(pb_stop.y, plc_101.stop) "command [IR if_ctl_04]";
    connect(pb_shut.y, plc_101.shut) "command [IR if_ctl_05]";
    connect(plc_101.valve1, xv_101.open) "open command [IR if_ctl_06]";
    connect(plc_101.valve2, xv_102.open) "open command [IR if_ctl_07]";
    connect(plc_101.valve3, xv_103.open) "open command [IR if_ctl_08]";
    connect(src_101.outlet, xv_101.inlet) "liquid [IR if_hyd_01]";
    connect(xv_101.outlet, tk_101.inlet) "liquid [IR if_hyd_02]";
    connect(tk_101.outlet, xv_102.inlet) "liquid [IR if_hyd_03]";
    connect(xv_102.outlet, tk_102.inlet) "liquid [IR if_hyd_04]";
    connect(tk_102.outlet, xv_103.inlet) "liquid [IR if_hyd_05]";
    connect(xv_103.outlet, drn_101.inlet) "liquid [IR if_hyd_06]";
    connect(tk_101.level, lt_101.u) "level [IR tk_101_lt_101]";
    connect(tk_102.level, lt_102.u) "level [IR tk_102_lt_102]";

    // ASSUMPTION (generator default): no output interval in the IR; Interval = (StopTime - StartTime) / 500 = 1.8 s, omc's default of 500 output intervals
    annotation(experiment(StopTime = 900.0, Interval = 1.8));
  end System;
end two_tank_sequence;
