// Generated by SpecAlive from the IR (specalive/generate/modelica.py). Regenerate, do not edit.
package system_model "Extracted from 12 source(s)."
  package SpecAlive "Lightweight equation-based components the catalogue can target"
    package Interfaces "Connectors of the SpecAlive components"
      connector RealInput = Modelica.Blocks.Interfaces.RealInput "Real signal input";
      connector RealOutput = Modelica.Blocks.Interfaces.RealOutput "Real signal output";
      connector BooleanInput = Modelica.Blocks.Interfaces.BooleanInput "Boolean signal input";
      connector BooleanOutput = Modelica.Blocks.Interfaces.BooleanOutput "Boolean signal output";
      connector VolumeFlowInput = input Real(unit = "m3/s") "Volume flow rate set by the connected component";
      connector VolumeFlowOutput = output Real(unit = "m3/s") "Volume flow rate set by this component";
    end Interfaces;

    package Components "Component classes used by this model"
      model CommandButton "Momentary pushbutton: true for one pulse width from each press time"
        parameter Real pressTimes[:](each unit = "s") = fill(0.0, 0) "Press times; none means never pressed";
        parameter Real width(unit = "s") = 1 "Pulse width of one press";
        SpecAlive.Interfaces.BooleanOutput y "True while pressed";
      protected
        Modelica.Blocks.Sources.BooleanTable table(table = {if mod(i, 2) == 1 then pressTimes[div(i + 1, 2)] else pressTimes[div(i, 2)] + width for i in 1:2 * size(pressTimes, 1)}, startValue = false) "Switches on at each press and off one width later";
      equation
        y = table.y;
      end CommandButton;

      model FluidSink "Ideal drain boundary: accepts whatever flow arrives"
        SpecAlive.Interfaces.VolumeFlowInput inlet "Flow delivered by the upstream component";
      end FluidSink;

      model FluidSource "Ideal supply boundary: delivers whatever flow downstream draws"
        SpecAlive.Interfaces.VolumeFlowInput outlet "Flow drawn by the downstream component";
      end FluidSource;

      model OnOffValve "Ideal Boolean flow switch: passes its nominal flow when open, none when closed"
        parameter Real q_nominal(unit = "m3/s") "Flow when open";
        SpecAlive.Interfaces.VolumeFlowOutput inlet "Flow drawn from upstream";
        SpecAlive.Interfaces.VolumeFlowOutput outlet "Flow delivered downstream";
        SpecAlive.Interfaces.BooleanInput open "True commands the valve open";
      equation
        outlet = if open then q_nominal else 0;
        inlet = outlet;
      end OnOffValve;

      model Tank "Open tank of constant cross-section: the level integrates inflow minus outflow"
        parameter Real A(unit = "m2") "Cross-section area";
        parameter Real h_start(unit = "m") "Initial level";
        SpecAlive.Interfaces.VolumeFlowInput inlet "Inflow, set by the upstream component";
        SpecAlive.Interfaces.VolumeFlowInput outlet "Outflow, set by the downstream component";
        SpecAlive.Interfaces.RealOutput level(unit = "m") "Liquid level";
        Real h(unit = "m", start = h_start, fixed = true) "Liquid level";
      equation
        der(h) = (inlet - outlet) / A;
        level = h;
      end Tank;
    end Components;
  end SpecAlive;

  model Controller_plc_101_sequence "State machine plc_101_sequence of PLC-101 [IR plc_101_sequence]"
    type State = enumeration(
      idle "IDLE",
      fill_t1 "FILL_T1",
      wait_after_fill "WAIT_AFTER_FILL",
      transfer_t1_t2 "TRANSFER_T1_T2",
      wait_after_transfer "WAIT_AFTER_TRANSFER",
      drain_t2 "DRAIN_T2",
      wait_after_drain "WAIT_AFTER_DRAIN",
      paused "PAUSED",
      shutdown "SHUTDOWN");
    SpecAlive.Interfaces.RealInput level1(unit = "m") "[IR plc_101_level1]";
    SpecAlive.Interfaces.RealInput level2(unit = "m") "[IR plc_101_level2]";
    SpecAlive.Interfaces.BooleanInput shut "[IR plc_101_shut]";
    SpecAlive.Interfaces.BooleanInput start "[IR plc_101_start]";
    SpecAlive.Interfaces.BooleanInput stop "[IR plc_101_stop]";
    SpecAlive.Interfaces.BooleanOutput valve1 "[IR plc_101_valve1]";
    SpecAlive.Interfaces.BooleanOutput valve2 "[IR plc_101_valve2]";
    SpecAlive.Interfaces.BooleanOutput valve3 "[IR plc_101_valve3]";
    parameter Real plc_101_wait_after_tank_1_high(unit = "s") "[IR plc_101_wait_after_tank_1_high]";
    parameter Real plc_101_wait_after_tank_1_low(unit = "s") "[IR plc_101_wait_after_tank_1_low]";
    parameter Real plc_101_wait_after_tank_2_low(unit = "s") "[IR plc_101_wait_after_tank_2_low]";
    parameter Real tk_101_high_level_limit(unit = "m") "[IR tk_101_high_level_limit]";
    parameter Real tk_101_low_level_limit(unit = "m") "[IR tk_101_low_level_limit]";
    parameter Real tk_102_low_level_limit(unit = "m") "[IR tk_102_low_level_limit]";
    State state(start = State.idle, fixed = true) "Active state";
    State history_state(start = State.idle, fixed = true) "State a history return goes back to";
    discrete Real wait_after_fill_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_fill_timer]";
    discrete Real wait_after_fill_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_fill_timer]";
    discrete Real wait_after_transfer_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_transfer_timer]";
    discrete Real wait_after_transfer_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_transfer_timer]";
    discrete Real wait_after_drain_timer_deadline(start = Modelica.Constants.inf, fixed = true) "Time the timer expires [IR wait_after_drain_timer]";
    discrete Real wait_after_drain_timer_remaining(start = 0, fixed = true) "Time left when frozen [IR wait_after_drain_timer]";
  algorithm
    when {
        edge(start),
        edge(stop),
        edge(shut),
        pre(state) == State.fill_t1 and level1 >= tk_101_high_level_limit,
        pre(state) == State.wait_after_fill and time >= wait_after_fill_timer_deadline,
        pre(state) == State.transfer_t1_t2 and level1 <= tk_101_low_level_limit,
        pre(state) == State.wait_after_transfer and time >= wait_after_transfer_timer_deadline,
        pre(state) == State.drain_t2 and level2 <= tk_102_low_level_limit,
        pre(state) == State.wait_after_drain and time >= wait_after_drain_timer_deadline,
        pre(state) == State.shutdown and level1 <= tk_101_low_level_limit and level2 <= tk_102_low_level_limit} then
      if pre(state) == State.idle then
        if edge(start) then
          // IR tr_idle_1: IDLE -> FILL_T1
          state := State.fill_t1;
        elseif edge(shut) then
          // IR tr_idle_3: IDLE -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.fill_t1 then
        if level1 >= tk_101_high_level_limit then
          // IR tr_fill_t1_1: FILL_T1 -> WAIT_AFTER_FILL
          wait_after_fill_timer_deadline := time + plc_101_wait_after_tank_1_high;
          state := State.wait_after_fill;
        elseif edge(stop) then
          // IR tr_fill_t1_2: FILL_T1 -> PAUSED
          history_state := State.fill_t1;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_fill_t1_3: FILL_T1 -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.wait_after_fill then
        if time >= wait_after_fill_timer_deadline then
          // IR tr_wait_after_fill_1: WAIT_AFTER_FILL -> TRANSFER_T1_T2
          state := State.transfer_t1_t2;
        elseif edge(stop) then
          // IR tr_wait_after_fill_2: WAIT_AFTER_FILL -> PAUSED
          history_state := State.wait_after_fill;
          wait_after_fill_timer_remaining := wait_after_fill_timer_deadline - time;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_wait_after_fill_3: WAIT_AFTER_FILL -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.transfer_t1_t2 then
        if level1 <= tk_101_low_level_limit then
          // IR tr_transfer_t1_t2_1: TRANSFER_T1_T2 -> WAIT_AFTER_TRANSFER
          wait_after_transfer_timer_deadline := time + plc_101_wait_after_tank_1_low;
          state := State.wait_after_transfer;
        elseif edge(stop) then
          // IR tr_transfer_t1_t2_2: TRANSFER_T1_T2 -> PAUSED
          history_state := State.transfer_t1_t2;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_transfer_t1_t2_3: TRANSFER_T1_T2 -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.wait_after_transfer then
        if time >= wait_after_transfer_timer_deadline then
          // IR tr_wait_after_transfer_1: WAIT_AFTER_TRANSFER -> DRAIN_T2
          state := State.drain_t2;
        elseif edge(stop) then
          // IR tr_wait_after_transfer_2: WAIT_AFTER_TRANSFER -> PAUSED
          history_state := State.wait_after_transfer;
          wait_after_transfer_timer_remaining := wait_after_transfer_timer_deadline - time;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_wait_after_transfer_3: WAIT_AFTER_TRANSFER -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.drain_t2 then
        if level2 <= tk_102_low_level_limit then
          // IR tr_drain_t2_1: DRAIN_T2 -> WAIT_AFTER_DRAIN
          wait_after_drain_timer_deadline := time + plc_101_wait_after_tank_2_low;
          state := State.wait_after_drain;
        elseif edge(stop) then
          // IR tr_drain_t2_2: DRAIN_T2 -> PAUSED
          history_state := State.drain_t2;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_drain_t2_3: DRAIN_T2 -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.wait_after_drain then
        if time >= wait_after_drain_timer_deadline then
          // IR tr_wait_after_drain_1: WAIT_AFTER_DRAIN -> FILL_T1
          state := State.fill_t1;
        elseif edge(stop) then
          // IR tr_wait_after_drain_2: WAIT_AFTER_DRAIN -> PAUSED
          history_state := State.wait_after_drain;
          wait_after_drain_timer_remaining := wait_after_drain_timer_deadline - time;
          state := State.paused;
        elseif edge(shut) then
          // IR tr_wait_after_drain_3: WAIT_AFTER_DRAIN -> SHUTDOWN
          state := State.shutdown;
        end if;
      elseif pre(state) == State.paused then
        if edge(start) then
          // IR tr_paused_1: PAUSED -> history
          history_state := State.idle;
          state := history_state;
          if history_state == State.wait_after_fill then wait_after_fill_timer_deadline := time + wait_after_fill_timer_remaining; end if;
          if history_state == State.wait_after_transfer then wait_after_transfer_timer_deadline := time + wait_after_transfer_timer_remaining; end if;
          if history_state == State.wait_after_drain then wait_after_drain_timer_deadline := time + wait_after_drain_timer_remaining; end if;
        end if;
      elseif pre(state) == State.shutdown then
        if level1 <= tk_101_low_level_limit and level2 <= tk_102_low_level_limit then
          // IR tr_shutdown_1: SHUTDOWN -> IDLE
          state := State.idle;
        end if;
      end if;
    end when;
  equation
    valve1 = state == State.fill_t1;
    valve2 = state == State.transfer_t1_t2 or state == State.shutdown;
    valve3 = state == State.drain_t2 or state == State.shutdown;
    assert(not (valve1 == true and valve2 == true) and not (valve2 == true and valve3 == true), "ac_08: Normal automatic operation shall never command V1 and V2 simultaneously, nor V2 and V3 simultaneously. The latter combination is permitted only in SHUTDOWN.");
  end Controller_plc_101_sequence;

  model System "system_model: one instance per IR part and one connect per IR connection"
    parameter Real plc_101_controller_scan_time(unit = "s") = 0.1 "plc_101 controller_scan_time [IR plc_101_controller_scan_time]";
    parameter Real plc_101_wait_after_tank_1_high(unit = "s") = 10.0 "plc_101 wait_after_tank_1_high [IR plc_101_wait_after_tank_1_high]";
    parameter Real plc_101_wait_after_tank_1_low(unit = "s") = 12.0 "plc_101 wait_after_tank_1_low [IR plc_101_wait_after_tank_1_low]";
    parameter Real plc_101_wait_after_tank_2_low(unit = "s") = 8.0 "plc_101 wait_after_tank_2_low [IR plc_101_wait_after_tank_2_low]";
    parameter Real system_logging_interval(unit = "s") = 1.0 "system logging_interval, verification only [IR system_logging_interval]";
    parameter Real system_simulation_stop_time(unit = "s") = 900.0 "system simulation_stop_time, verification only [IR system_simulation_stop_time]";
    // ASSUMPTION as_run_name_stop_time: 'simulation_stop_time' (900 s) is taken as the run's stop_time, the simulated run length or end time.
    parameter Real system_stop_time(unit = "s") = 900.0 "system stop_time, verification only [IR system_stop_time]";
    parameter Real tk_101_area(unit = "m2") = 1.2 "tk_101 area [IR tk_101_area]";
    parameter Real tk_101_high_level_limit(unit = "m") = 0.8 "tk_101 high_level_limit [IR tk_101_high_level_limit]";
    parameter Real tk_101_initial_level(unit = "m") = 0.05 "tk_101 initial_level [IR tk_101_initial_level]";
    parameter Real tk_101_initial_level_verification(unit = "m") = 0.05 "tk_101 initial_level, verification only [IR tk_101_initial_level_verification]";
    parameter Real tk_101_low_level_limit(unit = "m") = 0.05 "tk_101 low_level_limit [IR tk_101_low_level_limit]";
    parameter Real tk_102_area(unit = "m2") = 1.4 "tk_102 area [IR tk_102_area]";
    parameter Real tk_102_initial_level(unit = "m") = 0.05 "tk_102 initial_level [IR tk_102_initial_level]";
    parameter Real tk_102_initial_level_verification(unit = "m") = 0.05 "tk_102 initial_level, verification only [IR tk_102_initial_level_verification]";
    parameter Real tk_102_low_level_limit(unit = "m") = 0.05 "tk_102 low_level_limit [IR tk_102_low_level_limit]";
    parameter Real xv_101_nominal_flow(unit = "m3/s") = 0.006 "xv_101 nominal_flow [IR xv_101_nominal_flow]";
    parameter Real xv_102_nominal_flow(unit = "m3/s") = 0.0045 "xv_102 nominal_flow [IR xv_102_nominal_flow]";
    parameter Real xv_103_nominal_flow(unit = "m3/s") = 0.005 "xv_103 nominal_flow [IR xv_103_nominal_flow]";

    // ASSUMPTION as_stated_02: DRN-101 is treated as an ideal sink.
    SpecAlive.Components.FluidSink drn_101 "DRN-101 [IR drn_101]";
    Modelica.Blocks.Routing.RealPassThrough lt_101 "LT-101 [IR lt_101]";
    Modelica.Blocks.Routing.RealPassThrough lt_102 "LT-102 [IR lt_102]";
    SpecAlive.Components.CommandButton pb_shut "PB-SHUT [IR pb_shut]";
    SpecAlive.Components.CommandButton pb_start "PB-START [IR pb_start]";
    SpecAlive.Components.CommandButton pb_stop "PB-STOP [IR pb_stop]";
    Controller_plc_101_sequence plc_101(plc_101_wait_after_tank_1_high = plc_101_wait_after_tank_1_high, plc_101_wait_after_tank_1_low = plc_101_wait_after_tank_1_low, plc_101_wait_after_tank_2_low = plc_101_wait_after_tank_2_low, tk_101_high_level_limit = tk_101_high_level_limit, tk_101_low_level_limit = tk_101_low_level_limit, tk_102_low_level_limit = tk_102_low_level_limit) "PLC-101 [IR plc_101]";
    // ASSUMPTION as_stated_01: SRC-101 is treated as an ideal source.
    SpecAlive.Components.FluidSource src_101 "SRC-101 [IR src_101]";
    SpecAlive.Components.Tank tk_101(A = tk_101_area, h_start = tk_101_initial_level) "TK-101 [IR tk_101]";
    SpecAlive.Components.Tank tk_102(A = tk_102_area, h_start = tk_102_initial_level) "TK-102 [IR tk_102]";
    // ASSUMPTION as_stated_03: Constant-flow demo assumption.
    // ASSUMPTION as_stated_04: The dynamic valve stroke is neglected and each valve is treated as an ideal Boolean flow switch.
    SpecAlive.Components.OnOffValve xv_101(q_nominal = xv_101_nominal_flow) "XV-101 [IR xv_101]";
    // ASSUMPTION as_stated_03: Constant-flow demo assumption.
    // ASSUMPTION as_stated_04: The dynamic valve stroke is neglected and each valve is treated as an ideal Boolean flow switch.
    SpecAlive.Components.OnOffValve xv_102(q_nominal = xv_102_nominal_flow) "XV-102 [IR xv_102]";
    // ASSUMPTION as_stated_03: Constant-flow demo assumption.
    // ASSUMPTION as_stated_04: The dynamic valve stroke is neglected and each valve is treated as an ideal Boolean flow switch.
    SpecAlive.Components.OnOffValve xv_103(q_nominal = xv_103_nominal_flow) "XV-103 [IR xv_103]";
  equation
    connect(src_101.outlet, xv_101.inlet) "Liquid [IR if_hyd_01]";
    connect(xv_101.outlet, tk_101.inlet) "Liquid [IR if_hyd_02]";
    connect(tk_101.outlet, xv_102.inlet) "Liquid [IR if_hyd_03]";
    connect(xv_102.outlet, tk_102.inlet) "Liquid [IR if_hyd_04]";
    connect(tk_102.outlet, xv_103.inlet) "Liquid [IR if_hyd_05]";
    connect(xv_103.outlet, drn_101.inlet) "Liquid [IR if_hyd_06]";
    connect(lt_101.y, plc_101.level1) "signal_real [IR lt_101_level_out_to_plc_101_level1]";
    connect(lt_102.y, plc_101.level2) "signal_real [IR lt_102_level_out_to_plc_101_level2]";
    connect(pb_shut.y, plc_101.shut) "signal_bool [IR pb_shut_cmd_out_to_plc_101_shut]";
    connect(pb_start.y, plc_101.start) "signal_bool [IR pb_start_cmd_out_to_plc_101_start]";
    connect(pb_stop.y, plc_101.stop) "signal_bool [IR pb_stop_cmd_out_to_plc_101_stop]";
    connect(plc_101.valve1, xv_101.open) "signal_bool [IR plc_101_valve1_to_xv_101_cmd_in]";
    connect(plc_101.valve2, xv_102.open) "signal_bool [IR plc_101_valve2_to_xv_102_cmd_in]";
    connect(plc_101.valve3, xv_103.open) "signal_bool [IR plc_101_valve3_to_xv_103_cmd_in]";
    connect(tk_101.level, lt_101.u) "level [IR tk_101_level_out_to_lt_101_level_in]";
    connect(tk_102.level, lt_102.u) "level [IR tk_102_level_out_to_lt_102_level_in]";

    // ASSUMPTION (generator default): no output interval in the IR; Interval = (StopTime - StartTime) / 500 = 1.8 s, omc's default of 500 output intervals
    annotation(experiment(StopTime = 900.0, Interval = 1.8));
  end System;
end system_model;
